export const CHANGE_INPUT_VALUE = 'change_input_value'
export const ADD_LIST_VALUE = 'add_list_value'
export const DELETE_LIST_ITEM = 'delete_list_item'
export const INIT_LIST_VALUE = 'init_list_value'
export const GET_TODO_LIST = 'get_todo_list'
